name: Go

on:
  push:
    branches:
      - '*'  # Runs for every commit on any branch
    tags:
      - '*'  # Runs for tag pushes

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Read repository contents for running tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Test with the Go CLI
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test  # This job will only run if the 'test' job is successful
    permissions:
      contents: read  # Read repository contents for building
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        run: make build

  release:
    runs-on: ubuntu-latest
    needs: build  # This job will only run if the 'build' job is successful
    #if: startsWith(github.ref, 'refs/tags/')  # Check if the ref is a tag
    permissions:
      contents: write  # Write permissions to create releases
      packages: write  # Required for uploading artifacts if necessary
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
