name: ci-taskido

on:
  push:
    branches:
      - '*'  # Runs for every commit on any branch
    tags:
      - '*'  # Runs for tag pushes
    paths:
      - 'cmd/taskido/**'  # Only triggers when files under cmd/taskido/ are modified
      - 'internal/libtaskido/**'  # Only triggers when files under internal/libtaskido/ are modified
      - 'Makefile'  # Only triggers when Makefile is modified

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Test with the Go CLI
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        run: make build

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')  # Check if the ref is a tag
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
